services:
    mysql:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - ${MYSQL_PORT:-3306}:3306

    adminer:
        image: adminer
        ports:
            - 8001:8080
    
    mailcatcher:
        image: jeanberu/mailcatcher
        ports:
            - 1025:1025
            - 8002:1080
